// Omnipus - Ultra-lightweight personal AI agent
// License: MIT
// Copyright (c) 2026 Omnipus contributors

// criterion.go defines AcceptanceCriterion and its nested types (ADR-049 D2,
// spec Part A §C). Shared by task.Task.Criteria and (in pkg/plan) Plan.DoD —
// keep these types free of any pkg/task-specific dependency so pkg/plan can
// import them cleanly.
package task

import "github.com/google/uuid"

// CriterionKind discriminates a machine-checkable command from a free-text
// prose statement judged by the Judge System Agent.
type CriterionKind string

// The two criterion kinds (ADR D2).
const (
	KindCheck CriterionKind = "check"
	KindProse CriterionKind = "prose"
)

// IsValidCriterionKind reports whether k is a known criterion kind.
func IsValidCriterionKind(k CriterionKind) bool { return k == KindCheck || k == KindProse }

// CriterionStatus is the per-run judgement status of a criterion.
type CriterionStatus string

// The three criterion statuses. Absence of a verdict never defaults to
// CritMet (NFR-2) — a fresh/unjudged criterion is CritPending.
const (
	CritPending CriterionStatus = "pending"
	CritMet     CriterionStatus = "met"
	CritUnmet   CriterionStatus = "unmet"
)

// IsValidCriterionStatus reports whether s is a known criterion status.
func IsValidCriterionStatus(s CriterionStatus) bool {
	switch s {
	case CritPending, CritMet, CritUnmet:
		return true
	default:
		return false
	}
}

// maxCriterionTextRunes bounds AcceptanceCriterion.Text (spec Part A §C).
const maxCriterionTextRunes = 1000

// CriterionCheck is the machine-checkable half of a `kind: check` criterion.
// The command is dispatched through the assignee agent's existing `bash` tool
// machinery (ADR D2 rule 1) — same tool registry, policy resolution, sandbox
// enforcement, and audit trail as any other bash call.
type CriterionCheck struct {
	// Command is the shell command run through the assignee's bash tool.
	Command string `json:"command"`
	// ExpectedExitCode is the exit code that counts as PASS (met), 0..255.
	ExpectedExitCode int `json:"expected_exit_code"`
}

// CriterionAuthor records the identity of whoever authored a criterion (ADR D2
// rule 3). Mandatory on every criterion — author attribution is what lets a
// cross-agent-authored machine check require assignee-owner confirmation.
type CriterionAuthor struct {
	// Kind is "agent" or "user".
	Kind string `json:"kind"`
	// ID is the agent ID or username of the author.
	ID string `json:"id"`
}

// The two valid CriterionAuthor.Kind values.
const (
	AuthorKindAgent = "agent"
	AuthorKindUser  = "user"
)

// AcceptanceCriterion is one Definition-of-Done item on a Task (Task.Criteria)
// or a Plan (Plan.DoD, pkg/plan). Shared type — kept dependency-free so
// pkg/plan can import it without importing anything else from pkg/task.
type AcceptanceCriterion struct {
	// ID is the server-set criterion identifier (UUID). Generated by
	// normalizeCriteria when absent on a create-time payload.
	ID string `json:"id"`
	// Kind is check (machine-checkable) or prose (LLM-judged).
	Kind CriterionKind `json:"kind"`
	// Text is the criterion statement (prose) or a human-readable description
	// of what the check verifies (check). 1..1000 runes.
	Text string `json:"text"`
	// Check is required iff Kind == KindCheck; must be nil iff Kind ==
	// KindProse (no mixed shape, SD-A9).
	Check *CriterionCheck `json:"check,omitempty"`
	// Author records who authored this criterion (mandatory, ADR D2 rule 3).
	Author CriterionAuthor `json:"author"`
	// Status is the per-run judgement status; defaults to CritPending.
	Status CriterionStatus `json:"status"`
}

// normalizeCriteria server-sets a missing ID, defaults an empty Status to
// pending, and validates each criterion's shape (SD-A9, FR-014/015). It does
// NOT enforce "at least one criterion" (SD-A7's agent-path tiering) — that
// tiered rule depends on caller identity (agent tool vs. human/UI) which the
// store does not know; it is enforced by the caller.
func normalizeCriteria(criteria []AcceptanceCriterion) ([]AcceptanceCriterion, error) {
	for i := range criteria {
		c := &criteria[i]
		if c.ID == "" {
			c.ID = uuid.New().String()
		}
		if c.Status == "" {
			c.Status = CritPending
		}
		if err := validateCriterion(c, i); err != nil {
			return nil, err
		}
	}
	return criteria, nil
}

// NormalizeCriteria is the exported form of normalizeCriteria, for other
// packages that hold their own []AcceptanceCriterion slice needing the exact
// same shape validation this store applies to Task.Criteria — e.g. pkg/plan's
// Plan.DoD (ADR-049 D1), which is deliberately the SAME AcceptanceCriterion
// type so the judge, evidence, and verdict machinery are uniform across task
// and plan scopes. Same semantics as normalizeCriteria: server-sets a missing
// ID, defaults empty Status to pending, validates shape, and does NOT enforce
// "at least one criterion" (that tiered SD-A7 rule is the caller's job).
func NormalizeCriteria(criteria []AcceptanceCriterion) ([]AcceptanceCriterion, error) {
	return normalizeCriteria(criteria)
}

// validateCriterion validates a single criterion's shape (spec Part A §C /
// Dataset: Criterion validation). idx is used only to name the field in the
// returned error.
func validateCriterion(c *AcceptanceCriterion, idx int) error {
	if !IsValidCriterionKind(c.Kind) {
		return verr("criteria[%d]: invalid kind %q (must be \"check\" or \"prose\")", idx, c.Kind)
	}
	n := len([]rune(c.Text))
	if n < 1 {
		return verr("criteria[%d]: text is required", idx)
	}
	if n > maxCriterionTextRunes {
		return verr("criteria[%d]: text must be %d characters or fewer", idx, maxCriterionTextRunes)
	}
	switch c.Kind {
	case KindCheck:
		if c.Check == nil || c.Check.Command == "" {
			return verr("criteria[%d]: check criterion requires command", idx)
		}
		if c.Check.ExpectedExitCode < 0 || c.Check.ExpectedExitCode > 255 {
			return verr("criteria[%d]: expected_exit_code must be between 0 and 255", idx)
		}
	case KindProse:
		if c.Check != nil {
			return verr("criteria[%d]: prose criterion must not carry a check object", idx)
		}
	}
	if c.Author.Kind != AuthorKindAgent && c.Author.Kind != AuthorKindUser {
		return verr("criteria[%d]: author.kind must be \"agent\" or \"user\"", idx)
	}
	if c.Author.ID == "" {
		return verr("criteria[%d]: author.id is required", idx)
	}
	if !IsValidCriterionStatus(c.Status) {
		return verr("criteria[%d]: invalid status %q", idx, c.Status)
	}
	return nil
}
