// Omnipus - Ultra-lightweight personal AI agent
// License: MIT
// Copyright (c) 2026 Omnipus contributors

package sandbox

import (
	"fmt"
	"path/filepath"
	"strings"
)

// This file contains the pure, platform-independent Seatbelt profile
// generation logic. It has NO build constraint so it compiles (and is unit-
// tested) on Linux, while the actual SeatbeltBackend that consumes it lives in
// backend_darwin_seatbelt.go behind a `//go:build darwin` tag.
//
// Seatbelt is the macOS mandatory access-control subsystem (the XNU sandbox).
// The no-CGo path to apply it is to emit a Seatbelt profile (the `.sb`
// Scheme-like dialect) and launch the child under `/usr/bin/sandbox-exec -f`.
// This renderer maps an Omnipus SandboxPolicy onto that dialect.
//
// DRAFT (ADR-052 Phase-3 / AC-6): the renderer is complete and unit-tested,
// but the SeatbeltBackend that invokes sandbox-exec is gated behind
// OMNIPUS_SANDBELT_ENABLE=1 and is NOT wired into backend selection. macOS
// stays on FallbackBackend until a macOS integration test + adversarial review
// land. See backend_darwin_seatbelt.go.

// seatbeltExecPath is the signed Apple binary used to launch a child inside a
// Seatbelt profile. Shelling out to it is the documented viable no-CGo path to
// apply Seatbelt (the C sandbox_init(3) API would require CGo, which is
// forbidden by CLAUDE.md hard constraint #2). This is distinct from the
// "no ldd/os-exec for diagnostics" rule — sandbox-exec is the security
// enforcement primitive, not a diagnostic helper.
const seatbeltExecPath = "/usr/bin/sandbox-exec"

// renderSeatbeltProfile translates a SandboxPolicy into a Seatbelt `.sb`
// profile string. The posture mirrors the LinuxBackend (Landlock): default-
// deny with explicit allows derived from the policy.
//
// Field → directive mapping:
//
//   - FilesystemRules with AccessRead    → (allow file-read*  (subpath "..."))
//   - FilesystemRules with AccessWrite   → (allow file-write* (subpath "..."))
//   - FilesystemRules with AccessExecute → (allow process-exec (subpath "..."))
//     plus an implicit file-read* allow (a process cannot execute a file it
//     cannot read — Seatbelt, like every MAC system, requires read to mmap).
//   - BindPortRules    → (allow network-bind    (local  tcp "*:<port>"))
//   - ConnectPortRules → (allow network-outbound (remote tcp "*:<port>"))
//
// Network posture is strictly more conservative than Landlock's back-compat
// behavior: under (deny default) ALL network is denied, and only the ports
// enumerated in ConnectPortRules / BindPortRules are re-allowed. Landlock
// degrades to unrestricted networking when ConnectPortRules is empty (for
// pre-ABI-v4 kernel back-compat); Seatbelt is new code with no back-compat
// obligation, so empty port lists mean "no network". Callers that need
// outbound HTTPS must populate ConnectPortRules (DefaultPolicy seeds
// DefaultConnectPorts: 53/80/443 + the dev-server range).
//
// What this renderer deliberately does NOT add: the system-level allows a
// real macOS child needs to even start (dyld shared cache, /usr/lib,
// /dev/urandom, /Library/Preferences, process-fork, signal-self, etc.).
// Those are platform constants that must be validated empirically on macOS
// during the integration step; hardcoding them here from documentation would
// be guessing at a security boundary. The macOS reviewer appends a system
// preamble to the rendered workspace block. This keeps the renderer a faithful
// policy→profile mapper that is fully unit-testable on Linux.
func renderSeatbeltProfile(policy SandboxPolicy) (string, error) {
	if len(policy.FilesystemRules) == 0 && len(policy.BindPortRules) == 0 && len(policy.ConnectPortRules) == 0 {
		return "", fmt.Errorf("seatbelt: refusing to render a default-deny profile with zero allows (would brick any child); policy must enumerate at least the workspace path")
	}

	var b strings.Builder
	b.WriteString(";; Omnipus Seatbelt profile — DRAFT, generated by renderSeatbeltProfile.\n")
	b.WriteString(";; Posture: default-deny with explicit allows (mirrors Landlock).\n")
	b.WriteString(";; NOTE: a macOS system-library preamble (dyld, /usr/lib, /dev/urandom, …)\n")
	b.WriteString(";;       must be prepended at integration time for the child to start.\n")
	b.WriteString("(version 1)\n")
	b.WriteString("(deny default)\n")

	// --- Filesystem allows (policy order preserved; duplicates are the
	// caller's responsibility, same contract as Landlock). ---
	b.WriteString("\n;; --- Filesystem allows (from SandboxPolicy.FilesystemRules) ---\n")
	for _, rule := range policy.FilesystemRules {
		if err := validateSeatbeltPath(rule.Path); err != nil {
			return "", fmt.Errorf("seatbelt: filesystem rule path %q: %w", rule.Path, err)
		}
		sub := fmt.Sprintf("(subpath %q)", filepath.Clean(rule.Path))
		switch {
		case rule.Access == 0:
			return "", fmt.Errorf("seatbelt: filesystem rule for %q has no access flags", rule.Path)
		case rule.Access&AccessExecute != 0:
			// Execute implies read (must mmap the binary). Emit exec + read.
			b.WriteString("(allow process-exec " + sub + ")\n")
			b.WriteString("(allow file-read* " + sub + ")\n")
			if rule.Access&AccessWrite != 0 {
				b.WriteString("(allow file-write* " + sub + ")\n")
			}
		default:
			if rule.Access&AccessRead != 0 {
				b.WriteString("(allow file-read* " + sub + ")\n")
			}
			if rule.Access&AccessWrite != 0 {
				b.WriteString("(allow file-write* " + sub + ")\n")
			}
		}
	}

	// --- Network. Under (deny default) all network is already denied; the
	// explicit (deny network*) is emitted for auditor clarity and to make the
	// posture assertable in tests. Port allow-lists re-enable only what the
	// policy enumerates. ---
	b.WriteString("\n;; --- Network (default-deny; explicit port allow-list) ---\n")
	b.WriteString("(deny network*)\n")
	for _, r := range policy.BindPortRules {
		b.WriteString(fmt.Sprintf("(allow network-bind (local tcp \"*:%d\"))\n", r.Port))
	}
	for _, r := range policy.ConnectPortRules {
		b.WriteString(fmt.Sprintf("(allow network-outbound (remote tcp \"*:%d\"))\n", r.Port))
	}

	return b.String(), nil
}

// validateSeatbeltPath enforces that a path is safe to embed verbatim in a
// Seatbelt (subpath ...) filter. Seatbelt paths are literal double-quoted
// strings; a `"` or newline would break out of the filter and let an attacker
// inject profile directives (profile injection = full sandbox escape).
// Relative paths are rejected because (subpath "...") is interpreted relative
// to the sandbox-exec CWD, which would make the allow non-deterministic.
func validateSeatbeltPath(p string) error {
	if p == "" {
		return fmt.Errorf("path is empty")
	}
	if !filepath.IsAbs(p) {
		return fmt.Errorf("path must be absolute (relative paths resolve against sandbox-exec CWD)")
	}
	if strings.ContainsAny(p, "\"\n\r") {
		return fmt.Errorf("path contains a forbidden character (quote/newline) that could inject profile directives")
	}
	return nil
}
