// Omnipus — writing an inferred record type as a records.ParseSchema-shaped
// YAML file.
// License: MIT
// Copyright (c) 2026 Omnipus contributors

package vaultimport

import (
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/elicify-ai/omnipus/pkg/records"
)

// RenderSchemaYAML builds one <type>.yaml schema file's bytes from inferred
// properties, in the exact shape records.ParseSchema decodes: a bare
// `schema_version: 1` int, `type:`, and a `properties:` mapping in
// alphabetical property-name order (this package's own generation order —
// InferSchema already sorts, so re-sorting here is a formality, not a second
// decision).
//
// It is round-tripped against records.ParseSchema in
// schema_write_roundtrip_test.go — this file is the only place that builds
// this shape, and pkg/records is the only place that reads it back.
func RenderSchemaYAML(recordType string, props []InferredProperty) ([]byte, error) {
	propPairs := make([]ordPair, 0, len(props))
	for _, p := range props {
		propPairs = append(propPairs, ordPair{Key: p.Name, Value: renderPropertyDecl(p)})
	}
	top := orderedMap(
		ordPair{Key: "schema_version", Value: records.SupportedSchemaVersion},
		ordPair{Key: "type", Value: recordType},
		ordPair{Key: "properties", Value: orderedMap(propPairs...)},
	)
	return marshalDoc(top)
}

func renderPropertyDecl(p InferredProperty) *yaml.Node {
	pairs := []ordPair{{Key: "type", Value: string(p.Type)}}
	if p.Many {
		pairs = append(pairs, ordPair{Key: "many", Value: true})
	}
	if p.Required {
		pairs = append(pairs, ordPair{Key: "required", Value: true})
	}
	if p.Type == records.TypeEnum && len(p.EnumValues) > 0 {
		pairs = append(pairs, ordPair{Key: "values", Value: p.EnumValues})
	}
	if (p.Type == records.TypeRelation || p.Type == records.TypePerson) && p.To != "" {
		pairs = append(pairs, ordPair{Key: "to", Value: p.To})
	}
	return orderedMap(pairs...)
}

// ---------------------------------------------------------------------------
// A SCHEMA WITH NO NOTE BEHIND IT CARRIES ITS OWN ACCOUNT, IN THE FILE
//
// FR-018d provisioning (see run.go) declares a record type from a `.base`
// file when no note in the vault carries it. Everything about that
// declaration is an ASSUMPTION, and the founder's standing ruling on the
// importer's guesses is that a guess is acceptable when it is REPORTED and
// correctable in one edit.
//
// The report goes in the file rather than only in the console output, because
// the file is where the correction is made. An operator who opens
// `.omnipus-vault/records/compliance.yaml` six weeks after the import — long
// after the import log has scrolled away — reads, above the first property,
// that no note was consulted, which properties were assumed, which were
// deliberately left out and why, and the one command that fixes each.
//
// YAML comments are not data: records.ParseSchema decodes the document and
// never sees them, so the header cannot change what the schema means.
// ---------------------------------------------------------------------------

// RenderProvisionedSchemaYAML renders a schema DECLARED FROM A `.base` FILE
// with its provenance as a leading comment block. The document below the
// comment is byte-identical to what RenderSchemaYAML produces for the same
// properties — this adds a header, never a field.
func RenderProvisionedSchemaYAML(recordType string, props []InferredProperty, p ProvisionedType) ([]byte, error) {
	body, err := RenderSchemaYAML(recordType, props)
	if err != nil {
		return nil, err
	}
	var b strings.Builder
	b.WriteString("# GENERATED BY `omnipus records import` — DECLARED FROM A `.base` FILE, NOT FROM NOTES.\n")
	b.WriteString("#\n")
	for _, line := range p.ReportLines() {
		for _, wrapped := range wrapComment(line, 76) {
			b.WriteString("# ")
			b.WriteString(wrapped)
			b.WriteString("\n")
		}
	}
	b.WriteString("#\n")
	b.WriteString("# Edit this file, or run the `knowledge_configure` command above; either way the\n")
	b.WriteString("# next import leaves your edit alone, because a type real notes carry is never\n")
	b.WriteString("# re-declared from a base file.\n")
	b.Write(body)
	return []byte(b.String()), nil
}

// wrapComment breaks one account line into comment-width chunks on word
// boundaries. A single word longer than the width is left over-long rather
// than cut — a broken property name in a comment is worse than a long line.
func wrapComment(s string, width int) []string {
	words := strings.Fields(s)
	if len(words) == 0 {
		return []string{""}
	}
	var out []string
	cur := words[0]
	for _, w := range words[1:] {
		if len(cur)+1+len(w) > width {
			out = append(out, cur)
			cur = w
			continue
		}
		cur += " " + w
	}
	return append(out, cur)
}
