#!/usr/bin/env bash
# check-file-budget-selfcheck.sh
#
# Proves that scripts/check-file-budget.sh CAN fail. A guard that has never
# been seen to go red is not a guard — docs/internal/false-green-patterns.md
# records a guard test that passed 673/673 with the feature it guarded
# deleted. Same family as check-no-removed-providers-selfcheck.sh.
#
# Builds a throw-away synthetic tree and a throw-away budget file per case,
# and drives the real gate against them via its --root/--budget flags:
#
#   (a) a 3,156-line file NOT on the budget list          -> must FAIL
#       (one line over the 3,155 FAIL limit)
#   (b) a listed file one line UNDER its listed number    -> must pass (exit 0)
#   (c) a listed file one line OVER its listed number     -> must FAIL
#   (d) a 2,001-line file NOT on the list                 -> exactly one WARN,
#                                                             exit 0
#   (e) a 4,001-line file under an exempt generated/ dir  -> ignored entirely
#                                                             (exit 0, no
#                                                             WARN/FAIL lines)
#   (f) a file at exactly the 3,155 FAIL limit            -> WARN only, exit 0
#       (the gate fails OVER the limit, never AT it)
#
# Exit: 0 all cases behave, 1 a case misbehaves, 2 harness could not run.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHECK="$SCRIPT_DIR/check-file-budget.sh"

[ -f "$CHECK" ] || { echo "selfcheck: missing $CHECK" >&2; exit 2; }

TMP="$(mktemp -d "${TMPDIR:-/tmp}/file-budget-selfcheck.XXXXXX")" || exit 2
trap 'rm -rf "$TMP"' EXIT

FAIL=0

reset_tree() {
  rm -rf "$TMP/tree"
  mkdir -p "$TMP/tree/pkg"
}

make_file() { # make_file <relpath-under-tree> <lines>
  local rel="$1"
  local lines="$2"
  local path="$TMP/tree/$rel"
  mkdir -p "$(dirname "$path")"
  yes "x" | head -n "$lines" > "$path"
}

write_budget() { # write_budget <entry-lines...>
  {
    echo "# scripts/budgets/files.txt fixture (selfcheck)"
    echo "# path<TAB>lines — shrink-only"
    echo "# generated by check-file-budget-selfcheck.sh"
    for entry in "$@"; do
      printf '%s\n' "$entry"
    done
  } > "$TMP/budget.txt"
}

run_gate() {
  OUT="$("$CHECK" --root "$TMP/tree" --budget "$TMP/budget.txt" 2>&1)"
  RC=$?
}

expect_exit() { # expect_exit <label> <want-exit>
  local label="$1" want="$2"
  if [ "$RC" -ne "$want" ]; then
    echo "selfcheck FAIL: $label — wanted exit $want, got $RC" >&2
    printf '%s\n' "$OUT" | sed 's/^/    | /' >&2
    FAIL=1
    return 1
  fi
  echo "selfcheck ok:   $label (exit $RC)"
  return 0
}

# (a) 3,156-line unlisted file must FAIL (one line over the 3,155 limit).
reset_tree
make_file "pkg/a.go" 3156
write_budget
run_gate
if expect_exit "3,156-line unlisted file fails" 1; then
  if ! printf '%s\n' "$OUT" | grep -qE '^FAIL pkg/a\.go 3156 > 3155 \(not grandfathered\)$'; then
    echo "selfcheck FAIL: 3,156-line unlisted file — expected FAIL line not found" >&2
    printf '%s\n' "$OUT" | sed 's/^/    | /' >&2
    FAIL=1
  fi
fi

# (b) listed file one line under its listed number must pass.
reset_tree
make_file "pkg/b.go" 4999
write_budget "$(printf 'pkg/b.go\t5000')"
run_gate
expect_exit "listed file one line under its number passes" 0 || true

# (c) listed file one line over its listed number must FAIL.
reset_tree
make_file "pkg/c.go" 5001
write_budget "$(printf 'pkg/c.go\t5000')"
run_gate
if expect_exit "listed file one line over its number fails" 1; then
  if ! printf '%s\n' "$OUT" | grep -qE '^FAIL pkg/c\.go 5001 > listed 5000$'; then
    echo "selfcheck FAIL: listed-over-number case — expected FAIL line not found" >&2
    printf '%s\n' "$OUT" | sed 's/^/    | /' >&2
    FAIL=1
  fi
fi

# (d) 2,001-line unlisted file yields exactly one WARN and exit 0.
reset_tree
make_file "pkg/d.go" 2001
write_budget
run_gate
if expect_exit "2,001-line unlisted file warns only" 0; then
  warn_count="$(printf '%s\n' "$OUT" | grep -c '^WARN ' || true)"
  if [ "$warn_count" -ne 1 ]; then
    echo "selfcheck FAIL: 2,001-line unlisted file — expected exactly one WARN line, got $warn_count" >&2
    printf '%s\n' "$OUT" | sed 's/^/    | /' >&2
    FAIL=1
  elif ! printf '%s\n' "$OUT" | grep -qE '^WARN pkg/d\.go 2001 > 2000$'; then
    echo "selfcheck FAIL: 2,001-line unlisted file — WARN line has unexpected shape" >&2
    printf '%s\n' "$OUT" | sed 's/^/    | /' >&2
    FAIL=1
  fi
fi

# (e) a 4,001-line file under an exempt generated/ dir is ignored entirely.
reset_tree
make_file "pkg/api/generated/e.go" 4001
write_budget
run_gate
if expect_exit "generated/ file is ignored" 0; then
  finding_count="$(printf '%s\n' "$OUT" | grep -cE '^(WARN|FAIL) ' || true)"
  if [ "$finding_count" -ne 0 ]; then
    echo "selfcheck FAIL: generated/ file — expected no WARN/FAIL output, got $finding_count line(s)" >&2
    printf '%s\n' "$OUT" | sed 's/^/    | /' >&2
    FAIL=1
  fi
fi

# (f) a file at exactly the 3,155 FAIL limit warns only — the gate fails
# OVER the limit, never AT it.
reset_tree
make_file "pkg/f.go" 3155
write_budget
run_gate
if expect_exit "file at exactly the FAIL limit warns only" 0; then
  if ! printf '%s\n' "$OUT" | grep -qE '^WARN pkg/f\.go 3155 > 2000$'; then
    echo "selfcheck FAIL: at-limit file — expected WARN line not found" >&2
    printf '%s\n' "$OUT" | sed 's/^/    | /' >&2
    FAIL=1
  fi
fi

if [ "$FAIL" -ne 0 ]; then
  echo "selfcheck: check-file-budget.sh does not behave — see above" >&2
  exit 1
fi
echo "selfcheck: OK (check-file-budget.sh provably fails on offenders)"
exit 0
