package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/elicify-ai/omnipus/pkg/knowledge"
	"github.com/elicify-ai/omnipus/pkg/providers/catalog"
	systools "github.com/elicify-ai/omnipus/pkg/sysagent/tools"
	"github.com/elicify-ai/omnipus/pkg/tools"
	"github.com/elicify-ai/omnipus/pkg/tools/browser"
	"github.com/elicify-ai/omnipus/pkg/vaultprops"
)

const generatedHeader = "<!-- Generated by `go run ./cmd/docsref`; DO NOT EDIT BY HAND. -->"

type toolRow struct {
	Name        string
	Description string
	Auto        string
}

type toolGroup struct {
	Name  string
	Tools []toolRow
}

func renderProviders(doc *catalog.Document) string {
	var out strings.Builder
	fmt.Fprintf(&out, "%s\n\n# Providers and models\n\n", generatedHeader)
	out.WriteString("Tool use is catalog data. Omnipus sends tools with every request, so models marked **No** are not usable for agent requests.\n\n")
	out.WriteString("## Providers\n\n| Provider | Authentication | Tool use |\n|---|---|---|\n")
	for _, provider := range doc.Providers {
		fmt.Fprintf(&out, "| %s (`%s`) | %s | Unknown (not in catalog) |\n", escape(provider.Name), provider.ID, authLabel(provider.AuthMethods))
	}
	out.WriteString("\n## Models\n\n")
	for _, provider := range doc.Providers {
		fmt.Fprintf(&out, "### %s (`%s`)\n\n", escape(provider.Name), provider.ID)
		out.WriteString("| Models | Tool use |\n|---|---|\n")
		writeModelRows(&out, provider.Models)
		out.WriteByte('\n')
	}
	return strings.TrimSpace(out.String()) + "\n"
}

func authLabel(methods []catalog.AuthMethod) string {
	if len(methods) == 0 {
		return "Unknown (not in catalog)"
	}
	labels := make([]string, 0, len(methods))
	for _, method := range methods {
		switch method {
		case catalog.AuthAPIKey:
			labels = append(labels, "API key")
		case catalog.AuthSignIn:
			labels = append(labels, "sign in")
		default:
			labels = append(labels, escape(string(method)))
		}
	}
	return strings.Join(labels, ", ")
}

func writeModelRows(out *strings.Builder, models []catalog.Model) {
	byToolUse := map[bool][]string{}
	for _, model := range models {
		byToolUse[model.ToolCall] = append(byToolUse[model.ToolCall], "`"+strings.ReplaceAll(model.ID, "`", "\\`")+"`")
	}
	for _, supported := range []bool{true, false} {
		names := byToolUse[supported]
		if len(names) == 0 {
			continue
		}
		sort.Strings(names)
		fmt.Fprintf(out, "| %s | %s |\n", strings.Join(names, "<br>"), yesNo(supported))
	}
	if len(models) == 0 {
		out.WriteString("| Unknown (no models in catalog) | Unknown |\n")
	}
}

func renderTools(groups []toolGroup) string {
	var out strings.Builder
	fmt.Fprintf(&out, "%s\n\n# Built-in tools\n\n", generatedHeader)
	out.WriteString("The \"Under Auto\" column is ADR-092 D9's Auto-approve verdict — what happens " +
		"to a call to this tool, on Ask, when Auto-approve is on and the kernel sandbox is enforcing. " +
		"\"Runs\" never prompts. \"Runs if inside workspace\" prompts only when the call's file argument " +
		"resolves outside the workspace and its mounts. \"Asks\" always prompts (and is auto-denied in an " +
		"unattended run). `bash` keeps its own shell-permission mechanism (D3/D7/D8) and is not on this " +
		"scale.\n\n")
	for _, group := range groups {
		fmt.Fprintf(&out, "## %s\n\n| Tool | Description | Under Auto |\n|---|---|---|\n", group.Name)
		rows := append([]toolRow(nil), group.Tools...)
		sort.Slice(rows, func(i, j int) bool { return rows[i].Name < rows[j].Name })
		for _, row := range rows {
			fmt.Fprintf(&out, "| `%s` | %s | %s |\n", row.Name, escape(oneLine(row.Description)), row.Auto)
		}
		out.WriteByte('\n')
	}
	return strings.TrimSpace(out.String()) + "\n"
}

func oneLine(value string) string { return strings.Join(strings.Fields(value), " ") }

func escape(value string) string { return strings.ReplaceAll(value, "|", "\\|") }

func yesNo(value bool) string {
	if value {
		return "Yes"
	}
	return "No"
}

func writeReferences(outputDir string, doc *catalog.Document, groups []toolGroup) error {
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}
	files := []struct{ name, content string }{
		{"providers-and-models.md", renderProviders(doc)},
		{"built-in-tools.md", renderTools(groups)},
	}
	for _, file := range files {
		if err := os.WriteFile(filepath.Join(outputDir, file.name), []byte(file.content), 0o644); err != nil {
			return fmt.Errorf("write %s reference: %w", strings.TrimSuffix(file.name, ".md"), err)
		}
	}
	return nil
}

func toolRows(items []tools.Tool) []toolRow {
	rows := make([]toolRow, 0, len(items))
	for _, item := range items {
		rows = append(rows, toolRow{Name: item.Name(), Description: item.Description(), Auto: autoApproveLabel(item.Name())})
	}
	return rows
}

// autoApproveLabel renders the ADR-092 D9 classifier table
// (tools.AutoApproveClassOf, pkg/tools/auto_approve.go, §3) as the plain-
// English label used in the generated docs table. Reading straight from the
// table — rather than hand-maintaining prose per tool — is the point: the
// column cannot drift from the classifier the gateway and the agent loop
// actually consult.
func autoApproveLabel(name string) string {
	switch tools.AutoApproveClassOf(name) {
	case tools.AutoRuns:
		return "Runs"
	case tools.AutoRunsIfArgs:
		return "Runs if inside workspace"
	case tools.AutoShellMode:
		return "Own shell-permission mechanism"
	default: // tools.AutoAsks, including any tool with no explicit entry
		return "Asks"
	}
}

func staticToolGroups() []toolGroup {
	knowledgeTools := []tools.Tool{
		knowledge.NewDescribeTool(knowledge.ToolDeps{}, nil), vaultprops.NewFindTool(""),
		knowledge.NewReadTool(knowledge.ToolDeps{}), knowledge.NewListTool(knowledge.ToolDeps{}),
		knowledge.NewEditTool(knowledge.AuthoringDeps{}), knowledge.NewRestructureTool(knowledge.AuthoringDeps{}),
		knowledge.NewConfigureTool(knowledge.AuthoringDeps{}), knowledge.NewCreateBaseTool(knowledge.AuthoringDeps{}),
	}
	return []toolGroup{
		{Name: "System", Tools: toolRows(systools.AllTools(nil))},
		{Name: "General", Tools: toolRows(tools.GeneralBuiltinMetadata())},
		{Name: "Browser", Tools: toolRows(browser.BrowserBuiltinMetadata())},
		{Name: "Knowledge", Tools: toolRows(knowledgeTools)},
		{Name: "Grep", Tools: toolRows([]tools.Tool{tools.NewGrepTool("", false)})},
	}
}

func main() {
	outputDir := flag.String("output-dir", "docs/reference", "directory for generated reference files")
	flag.Parse()
	doc, err := catalog.ParseDocument(catalog.EmbeddedSnapshot)
	if err != nil {
		fmt.Fprintln(os.Stderr, "docsref: parse embedded provider catalog:", err)
		os.Exit(1)
	}
	if err := writeReferences(*outputDir, doc, staticToolGroups()); err != nil {
		fmt.Fprintln(os.Stderr, "docsref:", err)
		os.Exit(1)
	}
}
