package main

import (
	"os"
	"strings"
	"testing"

	"github.com/elicify-ai/omnipus/pkg/providers/catalog"
)

func TestRenderProvidersIncludesExactCatalogFactsAndUnknownProviderCapability(t *testing.T) {
	doc := &catalog.Document{Providers: []catalog.Provider{{
		ID:          "example",
		Name:        "Example | Cloud",
		AuthMethods: []catalog.AuthMethod{catalog.AuthAPIKey, catalog.AuthSignIn},
		Models: []catalog.Model{
			{ID: "model-tool", ToolCall: true},
			{ID: "model-plain", ToolCall: false},
		},
	}}}

	got := renderProviders(doc)
	wants := []string{
		"<!-- Generated by `go run ./cmd/docsref`; DO NOT EDIT BY HAND. -->",
		"| Example \\| Cloud (`example`) | API key, sign in | Unknown (not in catalog) |",
		"| `model-tool` | Yes |",
		"| `model-plain` | No |",
	}
	for _, want := range wants {
		if !strings.Contains(got, want) {
			t.Errorf("renderProviders() missing %q\noutput:\n%s", want, got)
		}
	}
}

func TestRenderProvidersSaysWhenAuthenticationIsUnknown(t *testing.T) {
	doc := &catalog.Document{Providers: []catalog.Provider{{ID: "local", Name: "Local"}}}

	got := renderProviders(doc)
	if !strings.Contains(got, "| Local (`local`) | Unknown (not in catalog) | Unknown (not in catalog) |") {
		t.Fatalf("renderProviders() did not make missing authentication explicit:\n%s", got)
	}
}

func TestRenderToolsGroupsAndSortsCatalogEntries(t *testing.T) {
	groups := []toolGroup{
		{Name: "General", Tools: []toolRow{{Name: "zeta", Description: "Last."}, {Name: "alpha", Description: "First | tool."}}},
		{Name: "System", Tools: []toolRow{{Name: "system.one", Description: "System tool."}}},
	}

	got := renderTools(groups)
	wants := []string{"<!-- Generated by `go run ./cmd/docsref`; DO NOT EDIT BY HAND. -->", "## General", "| `alpha` | First \\| tool. |", "| `zeta` | Last. |", "## System"}
	for _, want := range wants {
		if !strings.Contains(got, want) {
			t.Errorf("renderTools() missing %q\noutput:\n%s", want, got)
		}
	}
	if strings.Index(got, "`alpha`") > strings.Index(got, "`zeta`") {
		t.Errorf("renderTools() did not sort tools by name:\n%s", got)
	}
}

func TestWriteReferencesRejectsMissingOutputDirectory(t *testing.T) {
	blocker := t.TempDir() + "/file"
	if err := os.WriteFile(blocker, []byte("not a directory"), 0o600); err != nil {
		t.Fatal(err)
	}
	err := writeReferences(blocker+"/child", &catalog.Document{}, nil)
	if err == nil || !strings.Contains(err.Error(), "create output directory") {
		t.Fatalf("writeReferences() error = %v, want create output directory error", err)
	}
}
