/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppSkillsRouteImport } from './routes/_app/skills'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPoliciesRouteImport } from './routes/_app/policies'
import { Route as AppMonitorRouteImport } from './routes/_app/monitor'
import { Route as AppCommandCenterRouteImport } from './routes/_app/command-center'
import { Route as AppChannelsRouteImport } from './routes/_app/channels'
import { Route as AppAgentsRouteImport } from './routes/_app/agents'
import { Route as AppWorkspacesIndexRouteImport } from './routes/_app/workspaces.index'
import { Route as AppAgentsIndexRouteImport } from './routes/_app/agents.index'
import { Route as AppWorkspacesWorkspaceIdRouteImport } from './routes/_app/workspaces.$workspaceId'
import { Route as AppSessionsSessionIdRouteImport } from './routes/_app/sessions.$sessionId'
import { Route as AppAgentsAgentIdRouteImport } from './routes/_app/agents.$agentId'
import { Route as AppWorkspacesWorkspaceIdCalendarRouteImport } from './routes/_app/workspaces.$workspaceId.calendar'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPoliciesRoute = AppPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitorRoute = AppMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => AppRoute,
} as any)
const AppCommandCenterRoute = AppCommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsRoute = AppChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspacesIndexRoute = AppWorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsIndexRoute = AppAgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAgentsRoute,
} as any)
const AppWorkspacesWorkspaceIdRoute =
  AppWorkspacesWorkspaceIdRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => AppRoute,
  } as any)
const AppSessionsSessionIdRoute = AppSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsAgentIdRoute = AppAgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AppAgentsRoute,
} as any)
const AppWorkspacesWorkspaceIdCalendarRoute =
  AppWorkspacesWorkspaceIdCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AppWorkspacesWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/agents': typeof AppAgentsRouteWithChildren
  '/channels': typeof AppChannelsRoute
  '/command-center': typeof AppCommandCenterRoute
  '/monitor': typeof AppMonitorRoute
  '/policies': typeof AppPoliciesRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/tasks': typeof AppTasksRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/workspaces/$workspaceId': typeof AppWorkspacesWorkspaceIdRouteWithChildren
  '/agents/': typeof AppAgentsIndexRoute
  '/workspaces/': typeof AppWorkspacesIndexRoute
  '/workspaces/$workspaceId/calendar': typeof AppWorkspacesWorkspaceIdCalendarRoute
}
export interface FileRoutesByTo {
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/channels': typeof AppChannelsRoute
  '/command-center': typeof AppCommandCenterRoute
  '/monitor': typeof AppMonitorRoute
  '/policies': typeof AppPoliciesRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/tasks': typeof AppTasksRoute
  '/': typeof AppIndexRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/workspaces/$workspaceId': typeof AppWorkspacesWorkspaceIdRouteWithChildren
  '/agents': typeof AppAgentsIndexRoute
  '/workspaces': typeof AppWorkspacesIndexRoute
  '/workspaces/$workspaceId/calendar': typeof AppWorkspacesWorkspaceIdCalendarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/agents': typeof AppAgentsRouteWithChildren
  '/_app/channels': typeof AppChannelsRoute
  '/_app/command-center': typeof AppCommandCenterRoute
  '/_app/monitor': typeof AppMonitorRoute
  '/_app/policies': typeof AppPoliciesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/skills': typeof AppSkillsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/': typeof AppIndexRoute
  '/_app/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/_app/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/_app/workspaces/$workspaceId': typeof AppWorkspacesWorkspaceIdRouteWithChildren
  '/_app/agents/': typeof AppAgentsIndexRoute
  '/_app/workspaces/': typeof AppWorkspacesIndexRoute
  '/_app/workspaces/$workspaceId/calendar': typeof AppWorkspacesWorkspaceIdCalendarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/landing'
    | '/login'
    | '/onboarding'
    | '/agents'
    | '/channels'
    | '/command-center'
    | '/monitor'
    | '/policies'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/agents/$agentId'
    | '/sessions/$sessionId'
    | '/workspaces/$workspaceId'
    | '/agents/'
    | '/workspaces/'
    | '/workspaces/$workspaceId/calendar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/landing'
    | '/login'
    | '/onboarding'
    | '/channels'
    | '/command-center'
    | '/monitor'
    | '/policies'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/'
    | '/agents/$agentId'
    | '/sessions/$sessionId'
    | '/workspaces/$workspaceId'
    | '/agents'
    | '/workspaces'
    | '/workspaces/$workspaceId/calendar'
  id:
    | '__root__'
    | '/_app'
    | '/landing'
    | '/login'
    | '/onboarding'
    | '/_app/agents'
    | '/_app/channels'
    | '/_app/command-center'
    | '/_app/monitor'
    | '/_app/policies'
    | '/_app/settings'
    | '/_app/skills'
    | '/_app/tasks'
    | '/_app/'
    | '/_app/agents/$agentId'
    | '/_app/sessions/$sessionId'
    | '/_app/workspaces/$workspaceId'
    | '/_app/agents/'
    | '/_app/workspaces/'
    | '/_app/workspaces/$workspaceId/calendar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policies': {
      id: '/_app/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof AppPoliciesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitor': {
      id: '/_app/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof AppMonitorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/command-center': {
      id: '/_app/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof AppCommandCenterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels': {
      id: '/_app/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AppChannelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspaces/': {
      id: '/_app/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AppWorkspacesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/': {
      id: '/_app/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AppAgentsIndexRouteImport
      parentRoute: typeof AppAgentsRoute
    }
    '/_app/workspaces/$workspaceId': {
      id: '/_app/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/$sessionId': {
      id: '/_app/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AppSessionsSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/$agentId': {
      id: '/_app/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AppAgentsAgentIdRouteImport
      parentRoute: typeof AppAgentsRoute
    }
    '/_app/workspaces/$workspaceId/calendar': {
      id: '/_app/workspaces/$workspaceId/calendar'
      path: '/calendar'
      fullPath: '/workspaces/$workspaceId/calendar'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdCalendarRouteImport
      parentRoute: typeof AppWorkspacesWorkspaceIdRoute
    }
  }
}

interface AppAgentsRouteChildren {
  AppAgentsAgentIdRoute: typeof AppAgentsAgentIdRoute
  AppAgentsIndexRoute: typeof AppAgentsIndexRoute
}

const AppAgentsRouteChildren: AppAgentsRouteChildren = {
  AppAgentsAgentIdRoute: AppAgentsAgentIdRoute,
  AppAgentsIndexRoute: AppAgentsIndexRoute,
}

const AppAgentsRouteWithChildren = AppAgentsRoute._addFileChildren(
  AppAgentsRouteChildren,
)

interface AppWorkspacesWorkspaceIdRouteChildren {
  AppWorkspacesWorkspaceIdCalendarRoute: typeof AppWorkspacesWorkspaceIdCalendarRoute
}

const AppWorkspacesWorkspaceIdRouteChildren: AppWorkspacesWorkspaceIdRouteChildren =
  {
    AppWorkspacesWorkspaceIdCalendarRoute:
      AppWorkspacesWorkspaceIdCalendarRoute,
  }

const AppWorkspacesWorkspaceIdRouteWithChildren =
  AppWorkspacesWorkspaceIdRoute._addFileChildren(
    AppWorkspacesWorkspaceIdRouteChildren,
  )

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRouteWithChildren
  AppChannelsRoute: typeof AppChannelsRoute
  AppCommandCenterRoute: typeof AppCommandCenterRoute
  AppMonitorRoute: typeof AppMonitorRoute
  AppPoliciesRoute: typeof AppPoliciesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSessionsSessionIdRoute: typeof AppSessionsSessionIdRoute
  AppWorkspacesWorkspaceIdRoute: typeof AppWorkspacesWorkspaceIdRouteWithChildren
  AppWorkspacesIndexRoute: typeof AppWorkspacesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRouteWithChildren,
  AppChannelsRoute: AppChannelsRoute,
  AppCommandCenterRoute: AppCommandCenterRoute,
  AppMonitorRoute: AppMonitorRoute,
  AppPoliciesRoute: AppPoliciesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppTasksRoute: AppTasksRoute,
  AppIndexRoute: AppIndexRoute,
  AppSessionsSessionIdRoute: AppSessionsSessionIdRoute,
  AppWorkspacesWorkspaceIdRoute: AppWorkspacesWorkspaceIdRouteWithChildren,
  AppWorkspacesIndexRoute: AppWorkspacesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
